from database.tablebase import Base
from sqlalchemy import Column,String,Integer,Date,DateTime

class TimeSheet(Base):
    __tablename__ = 'timesheet'
    id = Column(Integer,autoincrement=True,primary_key=True)
    username = Column(String,nullable=False)
    approveusername = Column(String,nullable=False)
    year = Column(Integer,nullable=False)
    month = Column(Integer,nullable=False)
    day1 = Column(String)
    day2 = Column(String)
    day3 = Column(String)
    day4 = Column(String)
    day5 = Column(String)
    day6 = Column(String)
    day7 = Column(String)
    day8 = Column(String)
    day9 = Column(String)
    day10 = Column(String)
    day11 = Column(String)
    day12 = Column(String)
    day13 = Column(String)
    day14 = Column(String)
    day15 = Column(String)
    day16 = Column(String)
    day17 = Column(String)
    day18 = Column(String)
    day19 = Column(String)
    day20 = Column(String)
    day21 = Column(String)
    day22 = Column(String)
    day23 = Column(String)
    day24 = Column(String)
    day25 = Column(String)
    day26 = Column(String)
    day27 = Column(String)
    day28 = Column(String)
    day29 = Column(String)
    day30 = Column(String)
    day31 = Column(String)
    state = Column(String,nullable=False)
    submitdate = Column(Date)
    approvedate = Column(Date)

    def __repr__(self):
        return '<timesheet(username=%s,state=%s,submitdate=%s)>' % (self.username,self.state,self.submitdate)